apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-provider-backend-deployment
  namespace: saas-provider-backend
spec:
  template:
    spec:
      containers:
        - image: kiamol/ch02-hello-kiamol
          name: saas-provider-backend
