name: Deploy

on:
  push:
    branches:
      - main

env:
  # AWS_REGION: us-east-2
  # EKS_CLUSTER_NAME: saas-eks
  CLUSTER_NAME: liveproject-343323-gke
  CLUSTER_ZONE: europe-west2-b
  PROJECT_NAME: liveproject-343323

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Deploy
      #   uses: cancue/eks-action@v0.0.2
      #   env:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: $AWS_REGION
      #     cluster_name: $EKS_CLUSTER_NAME
      #   with:
      #     args: |
      #       kubectl apply -f argo-app.yaml -n argocd

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_NAME }}

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Deploy to the GKE cluster
      - name: Deploy
        run: |-
          kubectl apply -f argo-app-gcp.yaml -n argocd
